plugins {
    id 'kotlin'
    id 'com.google.devtools.ksp'
}

kotlin {
    jvmToolchain(11)
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    implementation "me.gulya.dagger:hilt-core:LOCAL-SNAPSHOT"
    ksp "me.gulya.dagger:hilt-compiler:LOCAL-SNAPSHOT"
}